Traceback (most recent call last):
  File "/home/larsm/mambaforge/envs/jupyterbook/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/larsm/mambaforge/envs/jupyterbook/lib/python3.11/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/larsm/mambaforge/envs/jupyterbook/lib/python3.11/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/larsm/mambaforge/envs/jupyterbook/lib/python3.11/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/larsm/mambaforge/envs/jupyterbook/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/larsm/mambaforge/envs/jupyterbook/lib/python3.11/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/larsm/mambaforge/envs/jupyterbook/lib/python3.11/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/larsm/mambaforge/envs/jupyterbook/lib/python3.11/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
min_kamp_1 = Counts(["URN:NBN:no-nb_digibok_2014032405041"])
min_kamp_1.head(20)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[7], line 2[0m
[1;32m      1[0m min_kamp_1 [38;5;241m=[39m Counts([[38;5;124m"[39m[38;5;124mURN:NBN:no-nb_digibok_2014032405041[39m[38;5;124m"[39m])
[0;32m----> 2[0m [43mmin_kamp_1[49m[38;5;241;43m.[39;49m[43mhead[49m[43m([49m[38;5;241;43m20[39;49m[43m)[49m

File [0;32m~/mambaforge/envs/jupyterbook/lib/python3.11/site-packages/dhlab/text/dhlab_object.py:31[0m, in [0;36mDhlabObj.head[0;34m(self, n)[0m
[1;32m     30[0m [38;5;28;01mdef[39;00m [38;5;21mhead[39m([38;5;28mself[39m, n[38;5;241m=[39m[38;5;241m5[39m):
[0;32m---> 31[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mfrom_df[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mframe[49m[38;5;241;43m.[39;49m[43mhead[49m[43m([49m[43mn[49m[43m)[49m[43m)[49m

File [0;32m~/mambaforge/envs/jupyterbook/lib/python3.11/site-packages/dhlab/text/conc_coll.py:207[0m, in [0;36mCounts.from_df[0;34m(cls, df)[0m
[1;32m    204[0m [38;5;129m@classmethod[39m
[1;32m    205[0m [38;5;28;01mdef[39;00m [38;5;21mfrom_df[39m([38;5;28mcls[39m, df):
[1;32m    206[0m     obj [38;5;241m=[39m Counts()
[0;32m--> 207[0m     [43mobj[49m[38;5;241;43m.[39;49m[43mcounts[49m [38;5;241m=[39m df
[1;32m    208[0m     obj[38;5;241m.[39mframe [38;5;241m=[39m df
[1;32m    209[0m     [38;5;28;01mreturn[39;00m obj

[0;31mAttributeError[0m: property 'counts' of 'Counts' object has no setter
AttributeError: property 'counts' of 'Counts' object has no setter

